<?php
/**
 * @var $note \PersonalNotebook\Api\Representation\NoteRepresentation|null
 * @var $resource \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null
 * @var $form \PersonalNotebook\Form\NoteForm
 */
?>

<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/personal-notebook.css', 'PersonalNotebook'));
$this->headScript()->appendFile($this->assetUrl('js/personal-notebook.js', 'PersonalNotebook'));
?>

<details class="personal-notebook-wrapper">
    <summary><?php echo $this->translate('Personal notes'); ?></summary>

    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formCollection($form, false); ?>
        <button type="submit"><?php echo $this->translate('Save my notes'); ?></button>
        <span class="personal-notebook-save-result"></span>
    <?php echo $this->form()->closeTag(); ?>
</details>
