<?php
/**
 * @var $notes \PersonalNotebook\Api\Representation\NoteRepresentation[]
 */
?>

<h2><?php echo $this->translate('Personal notes'); ?></h2>

<a href="<?php echo $this->url('site/personal-notebook/notes-csv', [], [], true); ?>"><?php echo $this->translate('Export all personal notes as CSV'); ?></a>

<div class="personal-notebook-table-wrapper">
    <?php foreach ($notes as $note): ?>
        <?php $resource = $note->resource(); ?>
        <div>
            <h3><?php echo $resource ? $resource->linkPretty() : $this->translate('Resource missing'); ?></h3>
            <?php echo $this->personalNotebook()->form($note); ?>
            <form id="personal-notebook-note-delete-form-<?php echo $note->id(); ?>" action="<?php echo $this->url('site/personal-notebook/notes-id', ['id' => $note->id(), 'action' => 'delete'], [], true); ?>" method="get">
                <input type="hidden" name="redirect_url" value="<?php echo $this->url(null, [], [], true); ?>">
                <button type="submit"><?php echo $this->translate('Delete'); ?></button>
            </form>
        </div>
    <?php endforeach; ?>
</div>
